import AppLayout from '@/components/AppLayot/AppLayout'
import './globals.css'
import { Shantell_Sans } from 'next/font/google'
import { UserContextProvider } from '@/context/user'

const inter = Shantell_Sans({ 
  subsets: ['cyrillic'],
  weight: "400",
  display: 'swap',
})

export const metadata = {
  title: 'WatsApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-[#e1e1dd]'>
      <body className={inter.className}>
        <UserContextProvider>
          <AppLayout>
            {children}
          </AppLayout>
        </UserContextProvider>
      </body>
    </html>
  )
}
